### ISSUE TITLE
he's not detecting on button click, he did not detect pressedButtonAtIndex

### ISSUE THREAD

**Issue by yafetsh** [pablogsIO/PGMenu#2]

**Comment by pablogsIO** [comment]
Hello, could you please tell me the steps to reproduce it? do you have an example?

Regards

**Comment by yafetsh** [comment]
Hi, it was a problem in my code, it works fine now, thank you

Le lun. 25 nov. 2019 à 20:09, Pablo Garcia <notifications@github.com> a
écrit :

**Comment by pablogsIO** [comment]
Thanks!
